### ISSUE TITLE
Helper can't be found

### ISSUE THREAD

**Issue by herzzanu** [Exelord/ember-initials#15]
Just installed the addon and I get the error `ember-initials is not a helper`

My project uses a pod structure and ember v2.10

Edit: extending the component does the trick. So it only works if I generate a component and extend the one from the add-on.

**Comment by Exelord** [comment]
Here was a similar problem. http://stackoverflow.com/questions/30323885/component-exposed-in-ember-addon-is-not-recognised-in-ember-app

Are u sure you install this addon through `ember install ember-initials` instead of adding it to `package.json` or using `npm install ember-initials`?

I checked the current version on a new fresh project and it works correctly unless I installed the package via npm.

**Comment by Exelord** [comment]
Hmm... I checked this package on a few real projects and it does work properly.
Could you try to reinstall addon, by removing it from package.json and execute install command again? I read that this could help. I also create a PR #17 which will improve addon private API and maybe this will fix your problem.

But to be honest, I never meet with an issue like that :/

**Comment by evoactivity** [comment]
I've installed it using `ember install ember-initials` tried reinstalling, tried `ember generate ember-initials` but that just says `Unknown blueprint: ember-initials`. Tried deleting node_modules and reinstalling with yarn, npm and `ember install`. Nothing worked. 😢 

I also generated a component and extended from the addon to make it work.

**Comment by Exelord** [comment]
Hi @evoactivity,
What version are you using? Do you get the same error: `ember-initials is not a helper`?
What's your ember-cli and ember version?

From [v3.1.0](https://github.com/Exelord/ember-initials/releases/tag/v3.1.0) there is no need to use `ember generate ember-initials` because the blueprint has been removed as well as `blueimp-md5` (bower dependency).

What you need now, is just to edit the version in package.json and `npm i`. I tested it on 2 projects and it works as expected.

Here is also a working twiddle: https://ember-twiddle.com/205fa2775fa1332248fb530971c65198?openFiles=templates.application.hbs%2C

**Comment by evoactivity** [comment]
@exelord 

Same error, yep.

Ember-Initials 3.1.0
Ember 2.10.2
ember-cli: 2.10.0

Also using pod structure.

I also setup a twiddle to confirm the addon worked and it did.
https://ember-twiddle.com/17c34feb7342719393d3f1c98a016571?openFiles=application.template.hbs%2C

I think this is probably something unique to our environments and will be very tricky to fix
